import '@/styles/globals.css'
import Head from 'next/head'
import type { AppProps } from 'next/app'
import { AliasProvider } from './../../context/AliasContext'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import { ResponseProvider } from 'context/ResponseContext'
import { AuthProvider } from 'context/AuthContext'

export default function App({ Component, pageProps }: AppProps) {
	return (
		<>
			<AuthProvider>
				<ResponseProvider>
					<AliasProvider>
						<Head>
							<title>Create Next App</title>
							<meta name='description' content='Generated by create next app' />
							<meta
								name='viewport'
								content='width=device-width, initial-scale=1'
							/>
							<link rel='icon' href='/favicon.ico' />
							<link
								href='https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css'
								rel='stylesheet'
								integrity='sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC'
								crossOrigin='anonymous'
							/>
							<script src='https://cdn.lordicon.com/bhenfmcm.js'></script>
						</Head>
						<Component {...pageProps} />
						<ToastContainer
							position='bottom-right'
							autoClose={5000}
							hideProgressBar={false}
							newestOnTop={false}
							closeOnClick
							rtl={false}
							pauseOnFocusLoss
							draggable
							pauseOnHover
							theme='dark'
						/>
					</AliasProvider>
				</ResponseProvider>
			</AuthProvider>
		</>
	)
}
